// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/factorstochvol.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvnorm
NumericVector dmvnorm(NumericMatrix x_, NumericMatrix means_, NumericVector vars_, const bool loga);
RcppExport SEXP _factorstochvol_dmvnorm(SEXP x_SEXP, SEXP means_SEXP, SEXP vars_SEXP, SEXP logaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type means_(means_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vars_(vars_SEXP);
    Rcpp::traits::input_parameter< const bool >::type loga(logaSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm(x_, means_, vars_, loga));
    return rcpp_result_gen;
END_RCPP
}
// predict
List predict(const List obj, const IntegerVector store, const int each);
RcppExport SEXP _factorstochvol_predict(SEXP objSEXP, SEXP storeSEXP, SEXP eachSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type store(storeSEXP);
    Rcpp::traits::input_parameter< const int >::type each(eachSEXP);
    rcpp_result_gen = Rcpp::wrap(predict(obj, store, each));
    return rcpp_result_gen;
END_RCPP
}
// sampler
List sampler(NumericMatrix y, const int draws, const int burnin, const List startval_in, const double bmu, const double Bmu, const NumericVector priorphi, const NumericVector Bsigma, const NumericVector priorbeta, const bool model_mean, const List shrinkagepriors, const int thin, const bool auxstore, const int thintime, const bool quiet, const int parameterization, const int MHsteps, const double B011_in, const double B022_in, const double MHcontrol, const bool Gammaprior, const double offset, const bool truncnormal, IntegerMatrix restr, const int interweaving, const bool signswitch, const int runningstore, const int runningstoreevery, const int runningstoremoments, const int pfl, const NumericVector sv, const NumericMatrix priorhomoskedastic, const NumericVector priorh0, const bool samplefac, const double facloadtol);
RcppExport SEXP _factorstochvol_sampler(SEXP ySEXP, SEXP drawsSEXP, SEXP burninSEXP, SEXP startval_inSEXP, SEXP bmuSEXP, SEXP BmuSEXP, SEXP priorphiSEXP, SEXP BsigmaSEXP, SEXP priorbetaSEXP, SEXP model_meanSEXP, SEXP shrinkagepriorsSEXP, SEXP thinSEXP, SEXP auxstoreSEXP, SEXP thintimeSEXP, SEXP quietSEXP, SEXP parameterizationSEXP, SEXP MHstepsSEXP, SEXP B011_inSEXP, SEXP B022_inSEXP, SEXP MHcontrolSEXP, SEXP GammapriorSEXP, SEXP offsetSEXP, SEXP truncnormalSEXP, SEXP restrSEXP, SEXP interweavingSEXP, SEXP signswitchSEXP, SEXP runningstoreSEXP, SEXP runningstoreeverySEXP, SEXP runningstoremomentsSEXP, SEXP pflSEXP, SEXP svSEXP, SEXP priorhomoskedasticSEXP, SEXP priorh0SEXP, SEXP samplefacSEXP, SEXP facloadtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const List >::type startval_in(startval_inSEXP);
    Rcpp::traits::input_parameter< const double >::type bmu(bmuSEXP);
    Rcpp::traits::input_parameter< const double >::type Bmu(BmuSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type priorphi(priorphiSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type Bsigma(BsigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type priorbeta(priorbetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type model_mean(model_meanSEXP);
    Rcpp::traits::input_parameter< const List >::type shrinkagepriors(shrinkagepriorsSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const bool >::type auxstore(auxstoreSEXP);
    Rcpp::traits::input_parameter< const int >::type thintime(thintimeSEXP);
    Rcpp::traits::input_parameter< const bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< const int >::type parameterization(parameterizationSEXP);
    Rcpp::traits::input_parameter< const int >::type MHsteps(MHstepsSEXP);
    Rcpp::traits::input_parameter< const double >::type B011_in(B011_inSEXP);
    Rcpp::traits::input_parameter< const double >::type B022_in(B022_inSEXP);
    Rcpp::traits::input_parameter< const double >::type MHcontrol(MHcontrolSEXP);
    Rcpp::traits::input_parameter< const bool >::type Gammaprior(GammapriorSEXP);
    Rcpp::traits::input_parameter< const double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const bool >::type truncnormal(truncnormalSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type restr(restrSEXP);
    Rcpp::traits::input_parameter< const int >::type interweaving(interweavingSEXP);
    Rcpp::traits::input_parameter< const bool >::type signswitch(signswitchSEXP);
    Rcpp::traits::input_parameter< const int >::type runningstore(runningstoreSEXP);
    Rcpp::traits::input_parameter< const int >::type runningstoreevery(runningstoreeverySEXP);
    Rcpp::traits::input_parameter< const int >::type runningstoremoments(runningstoremomentsSEXP);
    Rcpp::traits::input_parameter< const int >::type pfl(pflSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type priorhomoskedastic(priorhomoskedasticSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type priorh0(priorh0SEXP);
    Rcpp::traits::input_parameter< const bool >::type samplefac(samplefacSEXP);
    Rcpp::traits::input_parameter< const double >::type facloadtol(facloadtolSEXP);
    rcpp_result_gen = Rcpp::wrap(sampler(y, draws, burnin, startval_in, bmu, Bmu, priorphi, Bsigma, priorbeta, model_mean, shrinkagepriors, thin, auxstore, thintime, quiet, parameterization, MHsteps, B011_in, B022_in, MHcontrol, Gammaprior, offset, truncnormal, restr, interweaving, signswitch, runningstore, runningstoreevery, runningstoremoments, pfl, sv, priorhomoskedastic, priorh0, samplefac, facloadtol));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _factorstochvol_RcppExport_registerCCallable(void);

static const R_CallMethodDef CallEntries[] = {
    {"_factorstochvol_dmvnorm", (DL_FUNC) &_factorstochvol_dmvnorm, 4},
    {"_factorstochvol_predict", (DL_FUNC) &_factorstochvol_predict, 3},
    {"_factorstochvol_sampler", (DL_FUNC) &_factorstochvol_sampler, 35},
    {"_factorstochvol_RcppExport_registerCCallable", (DL_FUNC) &_factorstochvol_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_factorstochvol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
