# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm <- function(x_, means_, vars_, loga) {
    .Call(`_factorstochvol_dmvnorm`, x_, means_, vars_, loga)
}

predict <- function(obj, store, each) {
    .Call(`_factorstochvol_predict`, obj, store, each)
}

sampler <- function(y, draws, burnin, startval_in, bmu, Bmu, priorphi, Bsigma, priorbeta, model_mean, shrinkagepriors, thin, auxstore, thintime, quiet, parameterization, MHsteps, B011_in, B022_in, MHcontrol, Gammaprior, offset, truncnormal, restr, interweaving, signswitch, runningstore, runningstoreevery, runningstoremoments, pfl, sv, priorhomoskedastic, priorh0, samplefac, facloadtol) {
    .Call(`_factorstochvol_sampler`, y, draws, burnin, startval_in, bmu, Bmu, priorphi, Bsigma, priorbeta, model_mean, shrinkagepriors, thin, auxstore, thintime, quiet, parameterization, MHsteps, B011_in, B022_in, MHcontrol, Gammaprior, offset, truncnormal, restr, interweaving, signswitch, runningstore, runningstoreevery, runningstoremoments, pfl, sv, priorhomoskedastic, priorh0, samplefac, facloadtol)
}

